[project]
name = "cloud-run-whisper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi",
    "faster-whisper",
    "hypercorn",
    "uvicorn",
    "python-multipart",
    "pydantic-settings",
]

[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = [".venv", "build", "dist"]

[tool.ruff.lint]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "UP", # pyupgrade
  "B",  # bugbear
  "BLE",# blind except
]
ignore = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-q --cov=app --cov-report=term-missing:skip-covered"
testpaths = ["tests"]

[tool.uv]
dev-dependencies = [
  "ruff",
  "pytest",
  "httpx",
  "pytest-cov",
]